### ISSUE TITLE
Pattern 2.6 not Python 3 compatible

### ISSUE THREAD

**Issue by encolpe** [clips/pattern#140] opened 2016-01-22 10:38 UTC
Hello

I got this error when installing with Python 3.5:

``` bash
Downloading/unpacking pattern (from -r requirements.txt (line 6))
  Downloading pattern-2.6.zip (24.6MB): 24.6MB downloaded
  Running setup.py (path:/tmp/pip-build-c80fr52l/pattern/setup.py) egg_info for package pattern
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-c80fr52l/pattern/setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-c80fr52l/pattern/setup.py", line 40

    print n

          ^

SyntaxError: Missing parentheses in call to 'print'
```

**Comment by ExplodingCabbage** [comment] 2016-03-22 10:48
Duplicate of https://github.com/clips/pattern/issues/62, I think, and should probably be closed.

**Comment by tom-de-smedt** [comment] 2017-01-17 01:36
Please see #62

**Closed** 2017-06-06 11:16 UTC

**Comment by Myatsuwai** [comment] 2017-10-27 08:40
Hi,
To solve this problem in python3 (SyntaxError: Missing parentheses in call to 'print'), use () in print sentence.
for eg. 
print (n)
